version: '3'
services:
  hugo:
    container_name: ci22
    image: klakegg/hugo:latest
    command: server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    environment:
      VIRTUAL_HOST: ci22.local